import type { User, Message } from '../types';

export const currentUser: User = {
  id: 'current_user_1',
  name: 'Alex Mercer',
  username: 'alexmercer',
  role: 'Creative Developer',
  location: 'San Francisco, CA',
  bio: 'Building futuristic interactive web experiences. Passionate about WebGL, Framer Motion, and design systems.',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
  coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
  status: 'online',
  followersCount: 1240,
  followingCount: 482,
  skills: ['React', 'TypeScript', 'Three.js', 'Framer Motion', 'CSS/WebGL'],
  isFollowing: false
};

// export const mockUsers: User[] = [
//   {
//     id: 'user_1',
//     name: 'Sophia Chen',
//     username: 'sophiachen',
//     role: 'Lead UI/UX Designer',
//     location: 'Vancouver, BC',
//     bio: 'Designing user interfaces that tell stories. Crafting elegant digital products with a focus on typography and space.',
//     avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&w=800&q=80',
//     status: 'online',
//     followersCount: 3420,
//     followingCount: 652,
//     skills: ['Figma', 'UI Design', 'Interaction Design', 'Prototyping', 'System Design'],
//     isFollowing: true
//   },
//   {
//     id: 'user_2',
//     name: 'Marcus Vance',
//     username: 'marcusv',
//     role: 'Principal Frontend Engineer',
//     location: 'London, UK',
//     bio: 'Performance nerd and Web Assembly enthusiast. I love turning complex logic into smooth, fluid browser rendering.',
//     avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
//     status: 'online',
//     followersCount: 1890,
//     followingCount: 940,
//     skills: ['TypeScript', 'Rust', 'Vite', 'Next.js', 'Performance Tuning'],
//     isFollowing: false
//   },
//   {
//     id: 'user_3',
//     name: 'Elena Rostova',
//     username: 'elenarost',
//     role: 'Product Strategist',
//     location: 'Berlin, Germany',
//     bio: 'Connecting tech, design, and user needs to build meaningful SaaS products. Ex-Spotify, Ex-Stripe.',
//     avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&w=800&q=80',
//     status: 'away',
//     followersCount: 950,
//     followingCount: 180,
//     skills: ['Product Strategy', 'SaaS Growth', 'Agile Delivery', 'UX Research'],
//     isFollowing: false
//   },
//   {
//     id: 'user_4',
//     name: 'David Kim',
//     username: 'davidk',
//     role: 'Full Stack Engineer',
//     location: 'Seoul, South Korea',
//     bio: 'Building scalable backend systems and pixel-perfect frontends. Coffee drinker and open-source contributor.',
//     avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
//     status: 'offline',
//     followersCount: 620,
//     followingCount: 310,
//     skills: ['React', 'Node.js', 'PostgreSQL', 'GraphQL', 'Docker'],
//     isFollowing: false
//   },
//   {
//     id: 'user_5',
//     name: 'Aisha Rahman',
//     username: 'aishar',
//     role: '3D Artist & Motion Designer',
//     location: 'Dubai, UAE',
//     bio: 'Bringing static screens to life through 3D renders, particle systems, and kinetic typography. Blender lover.',
//     avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&w=800&q=80',
//     status: 'online',
//     followersCount: 5120,
//     followingCount: 1100,
//     skills: ['Blender', 'Spline 3D', 'After Effects', 'Web3 UI', 'Cinema 4D'],
//     isFollowing: true
//   },
//   {
//     id: 'user_6',
//     name: 'Leo Fontaine',
//     username: 'leofontaine',
//     role: 'Technical Writer & Developer Relations',
//     location: 'Paris, France',
//     bio: 'Bridging the gap between software engineers and product documentation. Organizer of tech meetups.',
//     avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
//     status: 'offline',
//     followersCount: 890,
//     followingCount: 420,
//     skills: ['DevRel', 'API Documentation', 'JavaScript', 'Community Building'],
//     isFollowing: false
//   },
//   {
//     id: 'user_7',
//     name: 'Priya Patel',
//     username: 'priyap',
//     role: 'Machine Learning Engineer',
//     location: 'Bangalore, India',
//     bio: 'Training neural nets by day, building AI-powered design tools by night. Fascinated by the intersection of ML and creativity.',
//     avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&w=800&q=80',
//     status: 'online',
//     followersCount: 2780,
//     followingCount: 560,
//     skills: ['Python', 'TensorFlow', 'PyTorch', 'Computer Vision', 'NLP'],
//     isFollowing: true
//   },
//   {
//     id: 'user_8',
//     name: 'James O\'Brien',
//     username: 'jamesob',
//     role: 'DevOps Architect',
//     location: 'Dublin, Ireland',
//     bio: 'Infrastructure as code evangelist. Automating everything from CI/CD pipelines to cloud-native deployments.',
//     avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
//     status: 'away',
//     followersCount: 1340,
//     followingCount: 490,
//     skills: ['Kubernetes', 'Terraform', 'AWS', 'GitHub Actions', 'Linux'],
//     isFollowing: false
//   },
//   {
//     id: 'user_9',
//     name: 'Yuki Tanaka',
//     username: 'yukit',
//     role: 'Creative Technologist',
//     location: 'Tokyo, Japan',
//     bio: 'Blending art and engineering with generative visuals, WebGL experiments, and interactive installations.',
//     avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&w=800&q=80',
//     status: 'online',
//     followersCount: 4200,
//     followingCount: 820,
//     skills: ['Three.js', 'GLSL', 'p5.js', 'TouchDesigner', 'WebXR'],
//     isFollowing: false
//   },
//   {
//     id: 'user_10',
//     name: 'Carlos Mendoza',
//     username: 'carlosm',
//     role: 'Mobile Engineer',
//     location: 'Mexico City, Mexico',
//     bio: 'Crafting delightful mobile experiences on iOS and Android. SwiftUI enthusiast and Kotlin multiplatform advocate.',
//     avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
//     status: 'online',
//     followersCount: 1560,
//     followingCount: 710,
//     skills: ['Swift', 'Kotlin', 'React Native', 'Flutter', 'Firebase'],
//     isFollowing: true
//   },
//   {
//     id: 'user_11',
//     name: 'Nina Petrova',
//     username: 'ninap',
//     role: 'Security Researcher',
//     location: 'Moscow, Russia',
//     bio: 'White hat hacker and penetration testing specialist. Making the web a safer place one vulnerability at a time.',
//     avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&w=800&q=80',
//     status: 'away',
//     followersCount: 980,
//     followingCount: 230,
//     skills: ['Cybersecurity', 'Pen Testing', 'OWASP', 'Network Security', 'CTF'],
//     isFollowing: false
//   },
//   {
//     id: 'user_12',
//     name: 'Omar Hassan',
//     username: 'omarh',
//     role: 'Data Engineer',
//     location: 'Cairo, Egypt',
//     bio: 'Building real-time data pipelines and analytics platforms. Apache Spark and Kafka are my daily tools.',
//     avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
//     status: 'offline',
//     followersCount: 740,
//     followingCount: 380,
//     skills: ['Apache Spark', 'Kafka', 'Airflow', 'Python', 'BigQuery'],
//     isFollowing: false
//   },
//   {
//     id: 'user_13',
//     name: 'Freya Lindqvist',
//     username: 'freyal',
//     role: 'Design Systems Lead',
//     location: 'Stockholm, Sweden',
//     bio: 'Obsessed with scalable design tokens, component libraries, and making designers and developers speak the same language.',
//     avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&w=800&q=80',
//     status: 'online',
//     followersCount: 2100,
//     followingCount: 540,
//     skills: ['Design Systems', 'Storybook', 'Figma', 'CSS Architecture', 'Accessibility'],
//     isFollowing: true
//   },
//   {
//     id: 'user_14',
//     name: 'Rafael Torres',
//     username: 'rafaelt',
//     role: 'Blockchain Developer',
//     location: 'Buenos Aires, Argentina',
//     bio: 'Building decentralized applications and smart contracts. Passionate about Web3 and financial inclusion.',
//     avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
//     status: 'online',
//     followersCount: 1870,
//     followingCount: 690,
//     skills: ['Solidity', 'Ethereum', 'Rust', 'DeFi', 'IPFS'],
//     isFollowing: false
//   },
//   {
//     id: 'user_15',
//     name: 'Mei Lin Wu',
//     username: 'meilinw',
//     role: 'Cloud Solutions Architect',
//     location: 'Taipei, Taiwan',
//     bio: 'Designing multi-cloud architectures that scale globally. AWS certified x5 and Google Cloud champion.',
//     avatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&w=800&q=80',
//     status: 'away',
//     followersCount: 3100,
//     followingCount: 450,
//     skills: ['AWS', 'GCP', 'Azure', 'Serverless', 'Microservices'],
//     isFollowing: false
//   },
//   {
//     id: 'user_16',
//     name: 'Liam Gallagher',
//     username: 'liamg',
//     role: 'Game Developer',
//     location: 'Melbourne, Australia',
//     bio: 'Indie game developer making retro-inspired pixel art games. Unity by day, Godot by night.',
//     avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
//     status: 'online',
//     followersCount: 2450,
//     followingCount: 880,
//     skills: ['Unity', 'C#', 'Godot', 'Pixel Art', 'Game Design'],
//     isFollowing: true
//   },
//   {
//     id: 'user_17',
//     name: 'Zara Okafor',
//     username: 'zarao',
//     role: 'Accessibility Engineer',
//     location: 'Lagos, Nigeria',
//     bio: 'Making the web usable for everyone. WCAG expert and screen reader testing advocate.',
//     avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&w=800&q=80',
//     status: 'online',
//     followersCount: 1680,
//     followingCount: 520,
//     skills: ['Accessibility', 'WCAG', 'ARIA', 'Screen Readers', 'Inclusive Design'],
//     isFollowing: false
//   },
//   {
//     id: 'user_18',
//     name: 'Nikolai Volkov',
//     username: 'nikolaiv',
//     role: 'Systems Programmer',
//     location: 'Prague, Czech Republic',
//     bio: 'Low-level systems programming in Rust and C++. Contributing to open-source compilers and runtime engines.',
//     avatar: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
//     status: 'offline',
//     followersCount: 920,
//     followingCount: 160,
//     skills: ['Rust', 'C++', 'LLVM', 'WebAssembly', 'Linux Kernel'],
//     isFollowing: false
//   },
//   {
//     id: 'user_19',
//     name: 'Ava Moretti',
//     username: 'avam',
//     role: 'Brand & Visual Designer',
//     location: 'Milan, Italy',
//     bio: 'Creating brand identities that resonate. From logo design to full visual systems. Typography is my love language.',
//     avatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&w=800&q=80',
//     status: 'online',
//     followersCount: 4700,
//     followingCount: 920,
//     skills: ['Branding', 'Typography', 'Illustrator', 'Visual Identity', 'Art Direction'],
//     isFollowing: true
//   },
//   {
//     id: 'user_20',
//     name: 'Ethan Brooks',
//     username: 'ethanb',
//     role: 'API Platform Engineer',
//     location: 'Austin, TX',
//     bio: 'Designing REST and GraphQL APIs that developers love. API-first development and developer experience matter.',
//     avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80',
//     coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
//     status: 'away',
//     followersCount: 1150,
//     followingCount: 470,
//     skills: ['GraphQL', 'REST', 'OpenAPI', 'Node.js', 'API Gateway'],
//     isFollowing: false
//   }
// ];

export const mockMessages: Message[] = [
  {
    id: 'msg_1',
    senderId: 'user_1',
    receiverId: 'current_user_1',
    content: "Hey Alex! Loved your recent interactive grid project. The micro-interactions were super smooth.",
    timestamp: '10:30 AM',
    isRead: true,
    type: 'text'
  },
  {
    id: 'msg_2',
    senderId: 'current_user_1',
    receiverId: 'user_1',
    content: "Thanks Sophia! It means a lot coming from you. Your Figma system templates have been a huge help for my mock layouts.",
    timestamp: '10:32 AM',
    isRead: true,
    type: 'text'
  },
  {
    id: 'msg_3',
    senderId: 'user_1',
    receiverId: 'current_user_1',
    content: "We should definitely collaborate on a WebGL template. Let me know if you want to hop on a call sometime this week!",
    timestamp: '10:33 AM',
    isRead: true,
    type: 'text'
  },
  {
    id: 'msg_4',
    senderId: 'user_2',
    receiverId: 'current_user_1',
    content: "Did you check out the new Vite 8 features yet? The bundling optimization is crazy fast.",
    timestamp: 'Yesterday',
    isRead: true,
    type: 'text'
  },
  {
    id: 'msg_5',
    senderId: 'user_5',
    receiverId: 'current_user_1',
    content: "Hey, do you have any tips for optimizing Spline loads inside React?",
    timestamp: 'Monday',
    isRead: true,
    type: 'text'
  }
];

// Interactive Bot Simulation Responses
export const botResponses: Record<string, string[]> = {
  user_1: [
    "That sounds fantastic! Let's arrange a call to discuss design constraints.",
    "I'm actually playing around with a new color scheme for our landing page right now. Let me send a draft soon.",
    "Could we try something with active particle triggers on click? It would look amazing.",
    "Absolutely! Let's build a UI system that feels extremely fluid.",
    "Awesome. I'll make a quick design concept and we can review it tomorrow."
  ],
  user_2: [
    "Yes, Rust with WebAssembly is definitely the path forward for this client-side processing.",
    "I ran a benchmark test and the rendering frame rate stayed solid at 120 FPS.",
    "We need to reduce the initial bundle size. Let's start lazy-loading our dashboard routes.",
    "I can jump on a voice call right now if you want to look at this Webpack config issue.",
    "Interesting problem. Let me look at the code repository in a bit."
  ],
  user_3: [
    "We should validate that assumption with user testing. I'll schedule research next week.",
    "The metrics show a 15% increase in user retention after we redesigned the onboarding transition.",
    "Let's focus on simplifying the chat route before we implement custom emojis.",
    "I've written down the product spec. Let me share the Notion doc.",
    "How does the development timeline look? Let me know if you need resources."
  ],
  user_5: [
    "I just finished a 3D glassmorphic card design in Spline. It looks beautiful!",
    "Definitely check if you're compressing your mesh size. It saves 80% on loading times.",
    "Are we planning to use custom canvas shaders for the landing hero background?",
    "Let's jump on a video call and walk through these motion curves. It will be much easier.",
    "Wow, that parallax effect is exactly what the project needed!"
  ],
  default: [
    "Hey! Thanks for the message. I'm currently focusing on a sprint, but I'll get back to you soon.",
    "Interesting! Let's chat more about this on a call.",
    "Sounds good. Send me the details or a link to review.",
    "Agreed. Let me know when you're available to sync.",
    "Awesome, let's keep iterating!"
  ]
};

// export const mockAttendees = {
//   alex: { name: 'Alex Mercer', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80' },
//   sophia: { name: 'Sophia Chen', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80' },
//   marcus: { name: 'Marcus Vance', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80' },
//   elena: { name: 'Elena Rostova', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80' },
//   david: { name: 'David Kim', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80' },
//   aisha: { name: 'Aisha Rahman', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80' },
//   leo: { name: 'Leo Fontaine', avatar: 'https://images.unsplash.com/photo-1500048993953-d23a436266cf?auto=format&fit=crop&w=150&q=80' },
//   ravi: { name: 'Ravi Shankar', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80' },
//   priya: { name: 'Priya Nair', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80' },
//   arjun: { name: 'Arjun Reddy', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80' },
//   meera: { name: 'Meera Joshi', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80' },
//   karthik: { name: 'Karthik Iyer', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80' },
//   nisha: { name: 'Nisha Gupta', avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=150&q=80' },
//   vikram: { name: 'Vikram Singh', avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80' },
//   anjali: { name: 'Anjali Menon', avatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=150&q=80' },
//   rohan: { name: 'Rohan Das', avatar: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=150&q=80' },
//   sneha: { name: 'Sneha Patil', avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=150&q=80' },
//   pranav: { name: 'Pranav Kulkarni', avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=crop&w=150&q=80' },
//   divya: { name: 'Divya Sharma', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=150&q=80' },
//   suresh: { name: 'Suresh Kumar', avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=150&q=80' },
//   lakshmi: { name: 'Lakshmi Rao', avatar: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?auto=format&fit=crop&w=150&q=80' },
//   amit: { name: 'Amit Patel', avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=150&q=80' }
// };

// export const communitiesData: CommunityItem[] = [
//   {
//     id: 'comm_1',
//     name: 'Koramangala Football Club',
//     theme: 'football',
//     image: 'https://assets.goal.com/images/v3/getty-2201476691/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORVGIYQ====/GettyImages-2201476691.jpg?auto=webp&format=pjpg&width=1080&quality=60',
//     status: 'Today',
//     dateStr: 'Today',
//     timeStr: '6:00 PM',
//     distance: '1.2 km away',
//     host: mockAttendees.alex,
//     attendees: [mockAttendees.sophia, mockAttendees.marcus, mockAttendees.elena, mockAttendees.david, mockAttendees.aisha, mockAttendees.ravi, mockAttendees.arjun, mockAttendees.karthik, mockAttendees.vikram, mockAttendees.rohan, mockAttendees.pranav, mockAttendees.suresh, mockAttendees.amit, mockAttendees.meera, mockAttendees.anjali]
//   },
//   {
//     id: 'comm_2',
//     name: 'Indiranagar Cricket League',
//     theme: 'cricket',
//     image: 'https://mediarelations.gwu.edu/sites/g/files/zaxdzs5306/files/2024-06/adobestock_510555809.jpeg',
//     status: 'Saturday',
//     dateStr: 'Saturday',
//     timeStr: '7:30 AM',
//     distance: '3.5 km away',
//     host: mockAttendees.sophia,
//     attendees: [mockAttendees.alex, mockAttendees.elena, mockAttendees.aisha, mockAttendees.marcus, mockAttendees.ravi, mockAttendees.priya, mockAttendees.arjun, mockAttendees.meera, mockAttendees.karthik, mockAttendees.nisha, mockAttendees.vikram, mockAttendees.anjali, mockAttendees.rohan, mockAttendees.sneha, mockAttendees.pranav, mockAttendees.divya, mockAttendees.suresh, mockAttendees.lakshmi, mockAttendees.amit]
//   },
//   {
//     id: 'comm_3',
//     name: 'Bangalore Jam Session',
//     theme: 'music',
//     image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=800&q=90',
//     status: 'Today',
//     dateStr: 'Today',
//     timeStr: '8:00 PM',
//     distance: '2.1 km away',
//     host: mockAttendees.marcus,
//     attendees: [mockAttendees.alex, mockAttendees.david, mockAttendees.sophia, mockAttendees.elena]
//   },
//   {
//     id: 'comm_4',
//     name: 'Happy Brew Bar Party',
//     theme: 'party',
//     image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=90',
//     status: 'Thursday',
//     dateStr: 'Next Thursday',
//     timeStr: '9:00 PM',
//     distance: '1.8 km away',
//     host: mockAttendees.elena,
//     attendees: [mockAttendees.sophia, mockAttendees.aisha, mockAttendees.alex]
//   },
//   {
//     id: 'comm_5',
//     name: 'Backpackers Travel Club',
//     theme: 'travel',
//     image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=90',
//     status: 'Ended',
//     dateStr: 'Yesterday',
//     timeStr: '10:00 AM',
//     distance: '4.5 km away',
//     host: mockAttendees.david,
//     attendees: [mockAttendees.marcus, mockAttendees.elena, mockAttendees.aisha, mockAttendees.alex, mockAttendees.sophia, mockAttendees.leo]
//   },
//   {
//     id: 'comm_6',
//     name: 'Mixology & Craft Beer Tour',
//     theme: 'drinks',
//     image: 'https://images.unsplash.com/photo-1574096079513-d8259312b785?auto=format&fit=crop&w=800&q=90',
//     status: 'Ended',
//     dateStr: 'Last Sunday',
//     timeStr: '6:30 PM',
//     distance: '2.8 km away',
//     host: mockAttendees.aisha,
//     attendees: [mockAttendees.elena, mockAttendees.sophia, mockAttendees.alex]
//   },
//   {
//     id: 'comm_7',
//     name: 'HSR Layout 5-a-Side Football',
//     theme: 'football',
//     image: 'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&w=800&q=90',
//     status: 'Saturday',
//     dateStr: 'Saturday',
//     timeStr: '5:00 PM',
//     distance: '2.4 km away',
//     host: mockAttendees.david,
//     attendees: [mockAttendees.alex, mockAttendees.marcus, mockAttendees.elena]
//   },
//   {
//     id: 'comm_8',
//     name: 'JP Nagar Sunday Football',
//     theme: 'football',
//     image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=90',
//     status: 'Today',
//     dateStr: 'Today',
//     timeStr: '7:00 AM',
//     distance: '3.8 km away',
//     host: mockAttendees.marcus,
//     attendees: [mockAttendees.sophia, mockAttendees.david, mockAttendees.aisha, mockAttendees.alex]
//   },
//   {
//     id: 'comm_9',
//     name: 'Whitefield Premier Cricket',
//     theme: 'cricket',
//     image: 'https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?auto=format&fit=crop&w=800&q=90',
//     status: 'Today',
//     dateStr: 'Today',
//     timeStr: '6:30 AM',
//     distance: '5.1 km away',
//     host: mockAttendees.alex,
//     attendees: [mockAttendees.marcus, mockAttendees.david, mockAttendees.leo]
//   },
//   {
//     id: 'comm_10',
//     name: 'BTM Gully Cricket Club',
//     theme: 'cricket',
//     image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=800&q=90',
//     status: 'Thursday',
//     dateStr: 'Next Thursday',
//     timeStr: '4:00 PM',
//     distance: '1.6 km away',
//     host: mockAttendees.elena,
//     attendees: [mockAttendees.sophia, mockAttendees.alex, mockAttendees.aisha, mockAttendees.marcus, mockAttendees.david]
//   },
//   {
//     id: 'comm_11',
//     name: 'Acoustic Nights Koramangala',
//     theme: 'music',
//     image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=90',
//     status: 'Saturday',
//     dateStr: 'Saturday',
//     timeStr: '9:00 PM',
//     distance: '0.8 km away',
//     host: mockAttendees.sophia,
//     attendees: [mockAttendees.alex, mockAttendees.elena, mockAttendees.marcus]
//   },
//   {
//     id: 'comm_12',
//     name: 'MG Road Open Mic & Beats',
//     theme: 'music',
//     image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=800&q=90',
//     status: 'Ended',
//     dateStr: 'Last Friday',
//     timeStr: '10:00 PM',
//     distance: '3.2 km away',
//     host: mockAttendees.aisha,
//     attendees: [mockAttendees.david, mockAttendees.sophia, mockAttendees.marcus, mockAttendees.alex, mockAttendees.elena]
//   }
// ];
